services:
  postgres:
    image: postgres:15.1-alpine
    ports:
      - 5432:5432
    volumes:
      - dbvol:/var/lib/postgresql/data
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PW}"
      POSTGRES_DB: "${POSTGRES_DB}"
  minio:
    image: minio/minio:RELEASE.2025-02-07T23-21-09Z
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
    command: server --console-address ":9001" /data
    volumes:
      - s3vol:/data
  mc:
    image: minio/mc
    depends_on:
      - minio
    volumes:
      - ./assets/images:/assets/images
    entrypoint: >
      /bin/sh -c "
      sleep 5 &&
      mc alias set local http://minio:9000 "${MINIO_ROOT_USER}" "${MINIO_ROOT_PASSWORD}" &&
      mc mb local/"${S3_BUCKET}" || true &&
      mc admin user add local "${AWS_ACCESS_KEY_ID}" "${AWS_SECRET_ACCESS_KEY}" &&
      mc admin policy attach local readwrite --user "${AWS_ACCESS_KEY_ID}" &&
      mc cp /assets/images/users/avatar.png local/"${S3_BUCKET}"/users/"${TEST_USER_ID}"/avatar.png &&
      mc cp /assets/images/beans/image.png local/"${S3_BUCKET}"/beans/1/image.png &&
      exit 0
      "
volumes:
  dbvol:
  s3vol: